version: "3.8"

services:
  backend:
    build:
      context: ./prod
      dockerfile: Dockerfile.backend
    container_name: yolo-backend
    ports:
      - "5003:5003"
    volumes:
      - ./runs:/app/runs # Mount YOLO model directory
    environment:
      FLASK_APP: app.py
      FLASK_ENV: production
      MODEL_PATH: /app/runs/detect/train3/weights/best.pt
      CORS_ORIGINS: "http://localhost:3000"
    restart: unless-stopped

  frontend:
    build:
      context: ./prod/frontend
      dockerfile: Dockerfile.frontend
    container_name: yolo-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_SOCKET_PROTOCOL: "http:"
      # For Docker service-to-service communication
      NEXT_PUBLIC_SOCKET_HOST: "backend"
      NEXT_PUBLIC_SOCKET_PORT: "5003"
      NEXT_PUBLIC_API_PROTOCOL: "http:"
      NEXT_PUBLIC_API_HOST: "backend"
      NEXT_PUBLIC_API_PORT: "5003"
    restart: unless-stopped
