version: "3.8"

services:
  backend:
    build:
      context: ./prod
      dockerfile: Dockerfile.backend
    container_name: yolo-backend
    ports:
      - "5003:5003"
    volumes:
      - ./runs:/app/runs # Mount YOLO model directory
    environment:
      FLASK_APP: app.py
      FLASK_ENV: production
      MODEL_PATH: /app/runs/detect/train3/weights/best.pt
      CORS_ORIGINS: "https://yolo.viewer.in,http://yolo.viewer.in,http://16.171.224.154:3000,http://16.171.224.154:3003,http://model.viewer.in:5003,https://model.viewer.in"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`model.viewer.in`)"
      - "traefik.http.services.backend.loadbalancer.server.port=5003"

  frontend:
    build:
      context: ./prod/frontend
      dockerfile: Dockerfile.frontend
    container_name: yolo-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_SOCKET_PROTOCOL: "http:"
      # For production use IP address and domain
      NEXT_PUBLIC_SOCKET_HOST: "16.171.224.154"
      NEXT_PUBLIC_SOCKET_PORT: "5003"
      NEXT_PUBLIC_API_PROTOCOL: "http:"
      NEXT_PUBLIC_API_HOST: "16.171.224.154"
      NEXT_PUBLIC_API_PORT: "5003"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`yolo.viewer.in`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
