version: "3.8"

services:
  backend:
    build:
      context: ./prod
      dockerfile: Dockerfile.backend
    container_name: yolo-backend
    ports:
      - "5003:5003"
    volumes:
      - ./runs:/app/runs # Mount YOLO model directory
    environment:
      FLASK_APP: app.py
      FLASK_ENV: production
      MODEL_PATH: /app/runs/detect/train3/weights/best.pt
      CORS_ORIGINS: "https://yolo.viewr.in,http://yolo.viewr.in,https://viewr.in,http://viewr.in,http://localhost:3000"
    restart: unless-stopped

  frontend:
    build:
      context: ./prod/frontend
      dockerfile: Dockerfile.frontend
    container_name: yolo-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_SOCKET_URL: ${SOCKET_URL}
      NEXT_PUBLIC_API_URL: ${API_URL}
    restart: unless-stopped
